import type { Candidate, Role, Stage } from "./types";

export const roles: Role[] = [
  {
    id: "product-engineer",
    title: "Senior Product Engineer",
    location: "San Francisco / Remote",
    openSince: "Open 18 days",
  },
  {
    id: "design-engineer",
    title: "Design Engineer",
    location: "New York / Remote",
    openSince: "Open 9 days",
  },
  {
    id: "platform-engineer",
    title: "Platform Engineer",
    location: "Remote, US",
    openSince: "Open 24 days",
  },
];

export const stages: Array<Stage | "All stages"> = [
  "All stages",
  "Sourced",
  "Screen",
  "Interview",
  "Offer",
];

export const candidates: Candidate[] = [
  {
    id: "alex-nguyen",
    name: "Alex Nguyen",
    initials: "AN",
    role: "Senior Product Engineer",
    location: "San Francisco, CA",
    email: "alex.nguyen@email.com",
    handle: "alexnguyen",
    stage: "Screen",
    match: 92,
    updated: "3h ago",
    accent: "#9fb9c6",
    summary:
      "Alex is a strong product engineer with deep TypeScript and React expertise and a track record of shipping high-impact features. He demonstrates solid API design and system design skills. The main gaps are fintech domain exposure and infrastructure ownership.",
    strengths: ["TypeScript", "React", "Product engineering", "System design", "API design"],
    risks: [
      "No direct fintech or financial services experience.",
      "Limited exposure to infrastructure and DevOps.",
      "Has not worked with Kotlin or native mobile.",
    ],
    evidence: [
      {
        requirement: "5+ years building product features end-to-end",
        detail: "6+ years shipping features from discovery to production across web and mobile.",
        source: "Resume · Work experience",
        status: "strong",
      },
      {
        requirement: "Strong in TypeScript and modern JavaScript",
        detail: "Extensive TypeScript in production codebases and open-source contributions.",
        source: "Resume · Top skills",
        status: "strong",
      },
      {
        requirement: "Experience with React or comparable framework",
        detail: "Built multiple React applications, component libraries, and design systems.",
        source: "Projects · Pulse Dashboard",
        status: "strong",
      },
      {
        requirement: "Design and ship scalable APIs",
        detail: "Designed REST and GraphQL APIs serving millions of requests daily.",
        source: "Work experience · 2020–2023",
        status: "strong",
      },
      {
        requirement: "Lead technical decisions and mentor engineers",
        detail: "Led a small team and mentored engineers on architecture and best practices.",
        source: "Leadership · Team lead",
        status: "partial",
      },
      {
        requirement: "Experience in fintech or financial services",
        detail: "No direct fintech experience found in the submitted profile.",
        source: "No evidence found",
        status: "missing",
      },
    ],
    interviewPlan: [
      { title: "Recruiter screen", duration: "30 min" },
      { title: "Technical deep dive", duration: "60 min" },
      { title: "System design", duration: "60 min" },
      { title: "Product sense", duration: "45 min" },
      { title: "Team fit", duration: "30 min" },
    ],
    activity: [
      { type: "note", title: "Note added by Jamie Lee", detail: "Discussed system design approach in screen.", time: "2h ago" },
      { type: "assessment", title: "Assessment completed", detail: "System design score: 84/100", time: "3h ago" },
      { type: "view", title: "Resume viewed by Jamie Lee", detail: "Candidate profile reviewed", time: "3h ago" },
      { type: "email", title: "Email sent by Jamie Lee", detail: "Re: Screening next steps", time: "1d ago" },
      { type: "added", title: "Candidate added", detail: "Imported from LinkedIn", time: "1d ago" },
    ],
  },
  {
    id: "maya-patel",
    name: "Maya Patel",
    initials: "MP",
    role: "Senior Product Engineer",
    location: "New York, NY",
    email: "maya.patel@email.com",
    handle: "mayapatel",
    stage: "Screen",
    match: 86,
    updated: "1d ago",
    accent: "#d9ab91",
    summary:
      "Maya combines strong frontend architecture with thoughtful product judgment. Her design systems work and customer-facing ownership stand out, while large-scale backend systems are a less proven area.",
    strengths: ["React", "Design systems", "Accessibility", "Product strategy", "GraphQL"],
    risks: ["Limited ownership of high-throughput backend systems.", "No direct native mobile experience."],
    evidence: [
      { requirement: "5+ years building product features end-to-end", detail: "Seven years across B2B SaaS products with ownership from research to launch.", source: "Resume · Experience", status: "strong" },
      { requirement: "Strong in TypeScript and modern JavaScript", detail: "Led TypeScript migration across three customer-facing applications.", source: "Case study · Platform", status: "strong" },
      { requirement: "Experience with React or comparable framework", detail: "Created an accessible React component system used by 11 teams.", source: "Portfolio · Design system", status: "strong" },
      { requirement: "Design and ship scalable APIs", detail: "Consumed and shaped GraphQL APIs; backend implementation was shared with platform.", source: "Interview notes", status: "partial" },
      { requirement: "Lead technical decisions and mentor engineers", detail: "Staff-level project leadership and formal mentorship for four engineers.", source: "Resume · Leadership", status: "strong" },
      { requirement: "Experience in fintech or financial services", detail: "Built invoicing and subscription experiences, but no regulated finance products.", source: "Resume · Billing", status: "partial" },
    ],
    interviewPlan: [
      { title: "Recruiter screen", duration: "30 min" },
      { title: "Portfolio review", duration: "60 min" },
      { title: "Architecture", duration: "60 min" },
      { title: "Product partnership", duration: "45 min" },
    ],
    activity: [
      { type: "note", title: "Portfolio note added", detail: "Strong accessibility rationale.", time: "1d ago" },
      { type: "view", title: "Profile reviewed", detail: "Reviewed by Morgan Chen", time: "1d ago" },
      { type: "added", title: "Candidate added", detail: "Employee referral", time: "2d ago" },
    ],
  },
  {
    id: "jordan-kim",
    name: "Jordan Kim",
    initials: "JK",
    role: "Product Engineer",
    location: "Austin, TX",
    email: "jordan.kim@email.com",
    handle: "jordankimdev",
    stage: "Interview",
    match: 78,
    updated: "2d ago",
    accent: "#8ba7a4",
    summary:
      "Jordan is a versatile product engineer with balanced frontend and backend experience. The profile shows strong delivery pace, though technical leadership and system scale need deeper validation.",
    strengths: ["Next.js", "Node.js", "PostgreSQL", "Rapid prototyping", "Customer discovery"],
    risks: ["Leadership scope is unclear.", "Most systems served early-stage traffic volumes."],
    evidence: [
      { requirement: "5+ years building product features end-to-end", detail: "Five years shipping startup products from prototype through paid launch.", source: "Resume · Experience", status: "strong" },
      { requirement: "Strong in TypeScript and modern JavaScript", detail: "Uses TypeScript across Next.js and Node.js services.", source: "GitHub · Projects", status: "strong" },
      { requirement: "Experience with React or comparable framework", detail: "Four production Next.js applications and internal tooling.", source: "Portfolio", status: "strong" },
      { requirement: "Design and ship scalable APIs", detail: "Built REST APIs and job workers; scale evidence remains limited.", source: "Technical screen", status: "partial" },
      { requirement: "Lead technical decisions and mentor engineers", detail: "Project lead experience, with no formal people mentorship listed.", source: "Resume", status: "partial" },
      { requirement: "Experience in fintech or financial services", detail: "Shipped payment reconciliation workflows for a marketplace.", source: "Work experience", status: "strong" },
    ],
    interviewPlan: [
      { title: "Technical screen", duration: "45 min" },
      { title: "Pairing session", duration: "75 min" },
      { title: "System design", duration: "60 min" },
      { title: "Founder chat", duration: "30 min" },
    ],
    activity: [
      { type: "assessment", title: "Coding exercise completed", detail: "Strong implementation, good tests.", time: "2d ago" },
      { type: "email", title: "Interview scheduled", detail: "Pairing session confirmed", time: "2d ago" },
      { type: "added", title: "Candidate added", detail: "Inbound application", time: "5d ago" },
    ],
  },
  {
    id: "taylor-reed",
    name: "Taylor Reed",
    initials: "TR",
    role: "Senior Product Engineer",
    location: "Seattle, WA",
    email: "taylor.reed@email.com",
    handle: "taylorreed",
    stage: "Sourced",
    match: 71,
    updated: "3d ago",
    accent: "#b8a491",
    summary:
      "Taylor brings mature platform instincts and strong cross-functional communication. Product UI depth is less visible in the profile, making the practical exercise an important signal.",
    strengths: ["Platform APIs", "Observability", "Python", "Mentorship", "Distributed systems"],
    risks: ["Recent work is backend-heavy.", "Limited evidence of polished customer-facing UI delivery."],
    evidence: [
      { requirement: "5+ years building product features end-to-end", detail: "Eight years in engineering, with recent focus on platform capabilities.", source: "Resume · Experience", status: "strong" },
      { requirement: "Strong in TypeScript and modern JavaScript", detail: "Some TypeScript service work; primary language is Python.", source: "Skills", status: "partial" },
      { requirement: "Experience with React or comparable framework", detail: "Contributed to internal React tools without primary ownership.", source: "Manager notes", status: "partial" },
      { requirement: "Design and ship scalable APIs", detail: "Owned APIs processing high-volume logistics and event data.", source: "Resume · Platform", status: "strong" },
      { requirement: "Lead technical decisions and mentor engineers", detail: "Technical lead for six engineers and established mentorship program.", source: "Resume · Leadership", status: "strong" },
      { requirement: "Experience in fintech or financial services", detail: "No relevant domain evidence found.", source: "No evidence found", status: "missing" },
    ],
    interviewPlan: [
      { title: "Recruiter screen", duration: "30 min" },
      { title: "Frontend practical", duration: "75 min" },
      { title: "Architecture", duration: "60 min" },
    ],
    activity: [
      { type: "email", title: "Outreach sent", detail: "Personalized role introduction", time: "3d ago" },
      { type: "view", title: "Profile sourced", detail: "Added to talent project", time: "3d ago" },
    ],
  },
  {
    id: "samuel-ortiz",
    name: "Samuel Ortiz",
    initials: "SO",
    role: "Product Engineer",
    location: "Denver, CO",
    email: "samuel.ortiz@email.com",
    handle: "samortiz",
    stage: "Sourced",
    match: 64,
    updated: "4d ago",
    accent: "#7e9aaa",
    summary:
      "Samuel has a solid application engineering foundation and clear learning velocity. The current profile is below the seniority target, but his fintech experience may justify a focused screen.",
    strengths: ["Vue", "Node.js", "Payments", "Testing", "Team collaboration"],
    risks: ["Below target seniority.", "Limited React experience.", "No evidence of technical leadership."],
    evidence: [
      { requirement: "5+ years building product features end-to-end", detail: "Three and a half years of full-stack product delivery.", source: "Resume · Experience", status: "partial" },
      { requirement: "Strong in TypeScript and modern JavaScript", detail: "Strong JavaScript and growing TypeScript ownership.", source: "GitHub · Projects", status: "partial" },
      { requirement: "Experience with React or comparable framework", detail: "Production Vue experience; React limited to side projects.", source: "Skills", status: "partial" },
      { requirement: "Design and ship scalable APIs", detail: "Built Node.js payment and identity APIs with strong test coverage.", source: "Work experience", status: "strong" },
      { requirement: "Lead technical decisions and mentor engineers", detail: "No leadership evidence in submitted materials.", source: "No evidence found", status: "missing" },
      { requirement: "Experience in fintech or financial services", detail: "Three years working on payments and transaction monitoring.", source: "Resume · Fintech", status: "strong" },
    ],
    interviewPlan: [
      { title: "Recruiter screen", duration: "30 min" },
      { title: "Technical calibration", duration: "45 min" },
      { title: "Pairing session", duration: "60 min" },
    ],
    activity: [
      { type: "note", title: "Sourcing note added", detail: "Fintech background may offset level gap.", time: "4d ago" },
      { type: "added", title: "Candidate added", detail: "Sourced from community", time: "4d ago" },
    ],
  },
];
